[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/netlify/*"
  to = "/index.html"
  status = 404
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
